# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Explorer(object):
    def setupUi(self, Explorer):
        Explorer.setObjectName("Explorer")
        Explorer.resize(1298, 796)
        self.centralwidget = QtWidgets.QWidget(Explorer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_top.setStyleSheet("background-color: rgb(120, 131, 148);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(5, 2, 2, 2)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_home = QtWidgets.QPushButton(self.frame_top)
        self.pb_home.setMinimumSize(QtCore.QSize(40, 35))
        self.pb_home.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_home.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.89, fx:0.5, fy:0.5, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(93, 93, 93, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:rgb(0, 0, 0);")
        self.pb_home.setObjectName("pb_home")
        self.horizontalLayout.addWidget(self.pb_home)
        self.textEdit = QtWidgets.QTextEdit(self.frame_top)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_main.setStyleSheet("background-color: rgb(80, 87, 100);")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.frame_main)
        self.splitter.setMidLineWidth(3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        self.treeView.setMinimumSize(QtCore.QSize(200, 0))
        self.treeView.setMaximumSize(QtCore.QSize(320, 16777215))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeView.setTabKeyNavigation(True)
        self.treeView.setObjectName("treeView")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.492925, y2:0.972, stop:0 rgba(24, 37, 54, 255), stop:1 rgba(81, 88, 100, 255));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QtWidgets.QListView(self.page)
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listView.setTabKeyNavigation(True)
        self.listView.setObjectName("listView")
        self.horizontalLayout_2.addWidget(self.listView)
        self.stackedWidget.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.page1)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.page1)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.page1)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page1)
        self.horizontalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame_main)
        Explorer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Explorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1298, 26))
        self.menubar.setObjectName("menubar")
        self.menuAffichage = QtWidgets.QMenu(self.menubar)
        self.menuAffichage.setObjectName("menuAffichage")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        Explorer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Explorer)
        self.statusbar.setObjectName("statusbar")
        Explorer.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAffichage.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(Explorer)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Explorer)

    def retranslateUi(self, Explorer):
        _translate = QtCore.QCoreApplication.translate
        Explorer.setWindowTitle(_translate("Explorer", "Explorer"))
        self.pb_home.setText(_translate("Explorer", "Home"))
        self.menuAffichage.setTitle(_translate("Explorer", "Affichage"))
        self.menuAide.setTitle(_translate("Explorer", "Aide"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Explorer = QtWidgets.QMainWindow()
    ui = Ui_Explorer()
    ui.setupUi(Explorer)
    Explorer.show()
    sys.exit(app.exec_())
